services:
  - type: web
    name: vote-trend-backend
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /
    scaling:
      minInstances: 1
      maxInstances: 1